name: Publicar Las 3 Yemitas

on:
  workflow_dispatch:

jobs:
  publicar:
    runs-on: ubuntu-latest
    steps:
      - name: Confirmar automatizacion
        run: echo "Automatizacion de Las 3 Yemitas funcionando"